### ISSUE TITLE
How to use api-console

### ISSUE THREAD

**Issue by kkai316** [WP-API/api-console#12]
Hello,
Can anyone tell me where should I put api-console with my wordpress folder and activate it? I am trying to auth api not to public but only who has the key. Can anyone give me a direction how to do it? I have been stuck for few days...
Thank you

**Comment by JessycaFrederick** [comment]
Yes, please provide the location where we're supposed to put these files.

**Comment by rmccue** [comment]
This plugin is deprecated, please use the [new version](https://github.com/WP-API/rest-api-console) instead. :)
